name: image-build

on:
  workflow_call:
    inputs:
      TEST1:
        required: true
        type: string
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cd1
        run: |
              echo "输出环境变量 ${{ inputs.TEST1 }} "
  build2:
    needs: build1
    uses: ./.github/workflows/call_kubespray.yaml
    secrets: inherit
    with:
      TEST2: ${{ inputs.TEST1 }}
