name: cd

on:
  workflow_call:
    inputs:
      ENVIRONMENT_RUNS_ON:
        required: true
        type: string
jobs:
  cd-to-demo-dev:
    runs-on: ${{ inputs.ENVIRONMENT_RUNS_ON }}
    steps:
      - name: cd
        run: |
              echo "${{ inputs.ENVIRONMENT_RUNS_ON }}"
