name: cd

on:
  workflow_call:
    inputs:
      enviroment:
        required: true
        type: string
jobs:
  cd-to-demo-dev:
    runs-on: ubuntu-latest
    steps:
      - name: cd
        run: |
              echo "${{ inputs.enviroment }}"
