name: call-test1

on:
  workflow_call:
    inputs:
      TEST1:
        required: true
        type: string
      AAA:
        required: true
        type: string
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cd1
        run: |
              echo "输出环境变量 ${{ inputs.TEST1 }} "
              echo "${{ inputs.TEST1 }} "
              echo $(echo "${{ inputs.SPRAY_REF }}" | cut -c 1-7)
              echo "输出环境变量 ${{ inputs.AAA }} "
              ASDF=${{ inputs.AAA }}
              echo $ASDF
  build2:
    needs: build1
    uses: ./.github/workflows/call-test2.yaml # 被调用的CI文件里再调用其他CI文件
    secrets: inherit
    with:
      TEST2: ${{ inputs.TEST1 }}
      AAA: ${{ inputs.AAA }}
