name: image-build

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  cd-to-demo-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cd1
        run: |
              echo "call_image_build输出环境变量 ${{ inputs.env }} "
              echo "call_image_build输出环境变量 ${env} " 
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ inputs.REF }}
  #     - name: cd2
  #       run: |
  #             cat README.md
  # build2:
  # needs: cd-to-demo-dev
  #   uses: ./.github/workflows/call_kubespray.yaml
  #   secrets: inherit
  #   with:
  #     ENVIRONMENT_RUNS_ON: ${ENVIRONMENT_RUNS_ON}
