name: E2E-Test

on: workflow_call

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: unit test
        run: |
            echo 你好啊
