name: cd

on: workflow_call

jobs:
  cd-to-demo-dev:
    runs-on: ubuntu-latest
    steps:
      - name: cd
        run: |
              # clean environment
              rm -rf *

              # install helm binary
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
              chmod 700 get_helm.sh
              ./get_helm.sh

              # helm install
              echo "${{secrets.DEV_KUBECONFIG}}" > kubeconfig
              helm list -A --kubeconfig kubeconfig
