name: main

on:
  push:
    branches:
      - main
env:
  TEST: "ubuntu-latest"

permissions:
  packages: write
  contents: read

jobs:
  output-variable: # 让build4传递环境变量必要的操作！！！
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.output_variables.outputs.test }}
      aaa: ${{ steps.output_variables.outputs.aaa }}
      tessst: ${{ steps.output_variables.outputs.tessst }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: kubernetes-sigs/kubespray
          ref: 3646dc0bd21d15025bf299270320eb50e7a3eec3
          
      - name: set environment variable
        run: |
          TESSST="我是TESSST"
          echo "TESSST=${TESSST,,}" >> ${GITHUB_ENV} # 由于每个job的文件系统都是独立的，本job产生的env没法被其他job使用

      - name: output environment variable
        id: output_variables
        run: |
          AAA="我是变量内容"
          echo ::set-output name=aaa::${AAA}
          echo ::set-output name=test::${{ env.TEST }}

          echo ::set-output name=tessst::${{ env.TESSST }}

  build1:
    needs: output-variable
    runs-on: ubuntu-latest
    steps:
      - name: test variable
        run: |
          echo "main输出变量 ${{ needs.output-variable.outputs.test }}"
          echo "main输出变量 ${{ needs.output-variable.outputs.aaa }}"

          echo "main输出变量  ${{ needs.output-variable.outputs.tessst }}"

  build2:
    needs: [build1,output-variable]
    uses: ./.github/workflows/call-test1.yaml
    secrets: inherit
    with:
      TEST1: ${{ needs.output-variable.outputs.test }} # 传递环境到同目录其他CI文件
      AAA: ${{ needs.output-variable.outputs.aaa }}
