name: main

on:
  push:
    branches:
      - main


# env:
#   KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
#   KUBESPRAY_IMAGE_NAME: kubespray
#   SPRAY_JOB_IMAGE_NAME: spray-job
#   ONLINE_REGISTER: ghcr.io

jobs:
  build1:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: unit test
        run: |
              echo "${{secrets.DEV_KUBECONFIG}}" > kubeconfig
              cat kubeconfig
              # curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
              # chmod 700 get_helm.sh
              # ./get_helm.sh
              helm list -A --kubeconfig kubeconfig



              
#            echo $GITHUB_REPOSITORY
#            echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
#            echo "REPO: ${{ env.REPO }}"
#            echo "${{ env.ONLINE_REGISTER }}/${{ env.REPO }}/kubespray:"
#             #VERSION=$GITHUB_REF_NAME
#             #echo $VERSION
  #
  # build2:
  #   needs: build1
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Checkout
  #     #   uses: actions/checkout@v2
  #     # - name: Release
  #     #   uses: softprops/action-gh-release@v1
  #     #   with:
  #     #     files: README.md
  #     - name: unit test
  #       run: |
  #           # echo ${{ secrets.TEST }}
  #           # echo 你们好哇 > test_${GITHUB_REF_NAME}_123.txt
  #           #
  #           # wget https://devtools.qiniu.com/qshell-v2.8.0-linux-amd64.tar.gz
  #           # tar -zxvf qshell-v2.8.0-linux-amd64.tar.gz
  #           # mv qshell /usr/local/bin/
  #           # qshell account -w ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} 'dce-ci'
  #           # # delete the same name of old file
  #           # qshell delete   ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/test_${GITHUB_REF_NAME}_123.txt
  #           # qshell rput   ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/test_${GITHUB_REF_NAME}_123.txt  ./test_${GITHUB_REF_NAME}_123.txt
  #           # rm -rf test_${GITHUB_REF_NAME}_123.txt
  #           # wget https://qiniu-download-public.daocloud.io/DaoCloud_Enterprise/dce5/test_${GITHUB_REF_NAME}_123.txt
  #           # cat test_${GITHUB_REF_NAME}_123.txt
  #           echo 12www3 > test_test_123.txt
  #           ls
  #
  #     - name: Upload output file
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: output-log-file-${GITHUB_REF_NAME}
  #         path: |
  #             test_main_123.txt
  #             test_test_123.txt
  # build3:
  #   needs: build2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: output-log-file-${GITHUB_REF_NAME}
  #     - name: unit test
  #       run: |
  #             cat test_test_123.txt

#   build4:
#     needs: build1
#     uses: ./.github/workflows/call_binary.yaml
#     secrets: inherit
