name: main

on:
  push:
    branches:
      - main
env:
  TEST: "ubuntu-latest"

permissions:
  packages: write
  contents: read

jobs:
  get-environment: # 让build4传递环境变量必要的操作！！！
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.get_variables.outputs.test }}
      aaa: ${{ steps.get_variables.outputs.aaa }}
      tessst: ${{ steps.get_variables.outputs.tessst }}

    steps:
      - name: set environment variable
        run: |
          TESSST="我是TESSST"
          echo "TESSST=${TESSST,,}" >> ${GITHUB_ENV} # 由于每个job的文件系统都是独立的，本job产生的env没法被其他job使用

      - name: Get environment variable
        id: get_variables
        run: |
          AAA="我是变量内容"
          echo ::set-output name=aaa::${AAA}
          echo ::set-output name=test::${{ env.TEST }}

          echo ::set-output name=tessst::${{ env.TESSST }}

  build1:
    needs: get-environment
    runs-on: ubuntu-latest
    steps:
      - name: unit test
        run: |
          echo "main输出变量 ${{ needs.get-environment.outputs.test }}"
          echo "main输出变量 ${{ needs.get-environment.outputs.aaa }}"

          echo "main输出变量  ${{ needs.get-environment.outputs.tessst }}"

  build2:
    needs: [build1,get-environment]
    uses: ./.github/workflows/call-test1.yaml
    secrets: inherit
    with:
      TEST1: ${{ needs.get-environment.outputs.test }} # 传递环境到同目录其他CI文件
      AAA: ${{ needs.get-environment.outputs.aaa }}
