name: main

on:
  push:
    branches:
      - main
env:
  TEST: "ubuntu-latest"

permissions:
  packages: write
  contents: read

jobs:
  get-environment:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.get_variables.outputs.test }}

    steps:
      - name: Get environment variable
        id: get_variables
        run: |
          echo ::set-output name=test::${{ env.TEST }}
  build1:
    needs: get-environment
    runs-on: ubuntu-latest
    steps:
      - name: unit test
        run: |
          echo "main输出变量 ${{ needs.get-environment.outputs.test }}"

  build4:
    needs: [build1,get-environment]
    uses: ./.github/workflows/call-test1.yaml
    secrets: inherit # 
    with:
      TEST1: ${{ needs.get-environment.outputs.test }}
