name: main

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

env:
  ENVIRONMENT_RUNS_ON: "ubuntu-latest"

permissions:
  packages: write
  contents: read

jobs:
  get_ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.result.outputs.ref }}
    steps:
      - name: Get Ref
        id: result
        run: |
          echo ::set-output name=ref::${{ github.event.pull_request.head.sha }}
  get-environment:
    needs: get_ref
    runs-on: ubuntu-latest
    steps:
      - name: Get environment variable
        run: |
          echo "输出目标信息 $GITHUB_SERVER    1"
          echo "输出目标信息 $GITHUB_REPOSITORY    2"
          echo "输出目标信息 ${{ needs.get_ref.outputs.ref }}    4"

  call-cd:
    uses: ./.github/workflows/call_image_build.yaml
    secrets: inherit
    needs: [get-environment,get_ref]
    with:
      REF: ${{ needs.get_ref.outputs.ref }}
      ENVIRONMENT_RUNS_ON: ${{ ENVIRONMENT_RUNS_ON }}
