name: main

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
env:
  ENVIRONMENT_RUNS_ON: "ubuntu-latest"

permissions:
  packages: write
  contents: read

jobs:
  get-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Get environment variable
        run: |
          echo "输出目标信息 $GITHUB_SERVER    1"
          echo "输出目标信息 $GITHUB_REPOSITORY    2"
          echo "输出目标信息 ${{ github.event.pull_request.head.sha }}    3"
