name: release

on: push

jobs:
  static-check:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: README.md
 
