name: release

on:
  push:
    branches:
      - main


env:
  KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
  KUBESPRAY_IMAGE_NAME: kubespray
  SPRAY_JOB_IMAGE_NAME: spray-job

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: README.md
      - name: unit test
        run: |
            VERSION=$GITHUB_REF_NAME
            echo $VERSION

  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: README.md
      - name: unit test
        run: |
            echo ${{ secrets.TEST }}
            echo 你们好哇 > test_123.txt

            wget https://devtools.qiniu.com/qshell-v2.8.0-linux-amd64.tar.gz
            tar -zxvf qshell-v2.8.0-linux-amd64.tar.gz
            mv qshell /usr/local/bin/
            qshell account -w ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} 'dce-ci'

            qshell delete   ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/test_123.txt
            qshell rput   ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/test_123.txt  ./test_123.txt
            rm -rf test_123.txt
            wget https://qiniu-download-public.daocloud.io/DaoCloud_Enterprise/dce5/test_123.txt
            cat test_123.txt
